include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    # Style
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true

    # Safety
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true

    # Flutter-specific
    use_build_context_synchronously: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
